"""Change version field type

Revision ID: 7f77cbc00305
Revises: 21ef5ce15822
Create Date: 2023-05-15 16:46:03.718794

"""

# revision identifiers, used by Alembic.
revision = "7f77cbc00305"
down_revision = "21ef5ce15822"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("plate_id", table_name="plate")
    op.create_index(op.f("ix_plate_plate_id"), "plate", ["plate_id"], unique=True)
    op.alter_column(
        "user", "email", existing_type=mysql.VARCHAR(length=128), nullable=False
    )
    op.drop_index("email", table_name="user")
    op.drop_index("google_id", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "avatar")
    op.drop_column("user", "google_id")
    op.alter_column(
        "plate",
        "method_document",
        existing_type=mysql.INTEGER(),
        type_=mysql.VARCHAR(length=128),
    )
    op.alter_column(
        "plate",
        "method_version",
        existing_type=mysql.INTEGER(),
        type_=mysql.VARCHAR(length=16),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plate",
        "method_version",
        existing_type=mysql.VARCHAR(length=16),
        type_=mysql.INTEGER(),
    )
    op.alter_column(
        "plate",
        "method_document",
        existing_type=mysql.VARCHAR(length=128),
        type_=mysql.INTEGER(),
    )

    op.add_column(
        "user", sa.Column("google_id", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column("user", sa.Column("avatar", mysql.TEXT(), nullable=True))
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("google_id", "user", ["google_id"], unique=False)
    op.create_index("email", "user", ["email"], unique=False)
    op.alter_column(
        "user", "email", existing_type=mysql.VARCHAR(length=128), nullable=True
    )
    op.drop_index(op.f("ix_plate_plate_id"), table_name="plate")
    op.create_index("plate_id", "plate", ["plate_id"], unique=False)
