"""Change version field type

Revision ID: ac3ae4a36f3a
Revises: 21ef5ce15822
Create Date: 2023-05-15 12:55:27.400475

"""

# revision identifiers, used by Alembic.
revision = 'ac3ae4a36f3a'
down_revision = '21ef5ce15822'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_analysis_rsnumber', table_name='genotype')
    op.drop_table('genotype')
    op.drop_table('sample')
    op.drop_table('snp')
    op.drop_index('_sample_type', table_name='analysis')
    op.drop_table('analysis')
    op.drop_index('email', table_name='user')
    op.drop_index('google_id', table_name='user')
    op.drop_table('user')
    op.drop_index('plate_id', table_name='plate')
    op.drop_table('plate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('plate_id', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('signed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_at', mysql.DATETIME(), nullable=True),
    sa.Column('method_document', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('method_version', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['signed_by'], ['user.id'], name='plate_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('plate_id', 'plate', ['plate_id'], unique=False)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('google_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('avatar', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('google_id', 'user', ['google_id'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('analysis',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', mysql.ENUM('genotype', 'sequence'), nullable=False),
    sa.Column('source', mysql.TEXT(), nullable=True),
    sa.Column('sex', mysql.ENUM('male', 'female', 'unknown'), nullable=True),
    sa.Column('sample_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('plate_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], ['plate.id'], name='analysis_ibfk_1'),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], name='analysis_sample'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('_sample_type', 'analysis', ['sample_id', 'type'], unique=False)
    op.create_table('snp',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('ref', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('chrom', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('pos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('sample',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('status', mysql.ENUM('pass', 'fail', 'cancel'), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('sex', mysql.ENUM('male', 'female', 'unknown'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('genotype',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rsnumber', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('analysis_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allele_1', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('allele_2', mysql.VARCHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], name='genotype_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('_analysis_rsnumber', 'genotype', ['analysis_id', 'rsnumber'], unique=False)
    # ### end Alembic commands ###
